# print(type(1))
# print(type(-10))
# print(type(0))
# print(type(0.0))
# print(10+3)
# print(45*9)
# print(100-99)
# print(78/6)
# print(8**9)
# print(4/2)
# print(100/2)
# print(3%2)
#
# print(pow(3,2))
# print(abs(-80))
# print(round(8.963))
# print(round(-3.14159, 6))
# print(bin(672))
# print(hex(655))
#
# age= input('What is your age?')
# age = int(age)
# pi = input('What is your pi?')
# pi = float(pi)


# 'Tadej Pogacar'.strip()
# 'Tadej Pogacar'.strip('d')

# print(bool(None))
# print(bool(False))
# print(bool(0))
# print(bool(0.0))
# print(bool([]))
# print(bool(()))
# print(bool({}))
# print(bool(''))
# print(bool(range(10)))
